name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: vijay80050
          template: classic
          base: header, activity, repositories
          plugin_isocalendar: yes
          config_timezone: Asia/Kolkata
